import DALogo from '../assets/DataAnnotation_Logo.jpg';
import '../global.css';

export function Experience() {
  return (
    <div className="text-start fs-8 w-80 mt-5 p-4 border-0 rounded blur shadow-sm">
      <h3 className='text-light text-center mb-4 text-uppercase tracking-wider' style={{ letterSpacing: '1px' }}>Experience</h3>

      <div className="mb-4 ps-2">
        <div className="d-flex align-items-center mb-1">
          <img src={DALogo} alt="DataAnnotation Logo" className="me-3" style={{ width: '30px' }} />
          <h5 className="text-light mb-0 fw-bold">DataAnnotation</h5>
        </div>
        
        <div className="text-light ps-5 ms-1">
          <div className="fw-semibold">AI Training (Software Engineering)</div>
          <div className="opacity-75 small mb-3">March 2024 - June 2025 | Remote</div>

          <ul className="small">
            <li className="mb-2">
              Validated and optimized code partially or fully generated by large language models across frontend (React), backend (Node.js, Flask), and systems (C, C++).
            </li>
            <li>
              Performed reinforcement learning and annotations on code outputs to improve the model's performance for future iterations.
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}